# Generated by Django 4.0.2 on 2022-03-06 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='payment_status',
        ),
    ]
