# Generated by Django 4.0.2 on 2022-03-06 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_today_date_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='currency',
        ),
    ]
