# Generated by Django 4.0.2 on 2022-03-06 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_user_order_name_alter_order_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='user',
        ),
    ]
