# Generated by Django 4.0.2 on 2022-03-06 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_name_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
