# Generated by Django 4.0.2 on 2022-03-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_amount', models.IntegerField()),
            ],
        ),
    ]
