# Generated by Django 4.0.2 on 2022-03-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='url',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
